### PR TITLE
fix(core): Respect publishConfig.directory in npm publish workflow

### LINKED ISSUE #4079: Angular Admin UI compilation fails in Vendure 3.5.2 due to missing package exports
**Describe the bug**
After upgrading from Vendure 3.5.1 to 3.5.2, the Angular Admin UI compilation fails with module resolution errors. The `@vendure/admin-ui` package's `exports` field in `package.json` only exports the root path (`.`), but the compiled Admin UI extensions attempt to import from subpaths like `@vendure/admin-ui/core`, `@vendure/admin-ui/login`, etc., which are no longer exported.

Vendure: 3.5.2 (upgraded from 3.5.1)
Node: v22.12.0
npm: 11.5.2
Angular: 19.2.4
Error count: 200+ compilation errors
Root cause: The exports field in node_modules/@vendure/admin-ui/package.json only includes: 
"exports": {
    ".": { ... }
}

**To Reproduce**
## Package Versions
```json
{
  "@vendure/admin-ui": "^3.5.2",
  "@vendure/admin-ui-plugin": "3.5.2",
  "@vendure/ui-devkit": "3.5.2",
  "@vendure/core": "3.5.2",
  "@angular-devkit/build-angular": "^19.2.10",
  "@angular/animations": "^19.2.9",
  "@angular/platform-browser-dynamic": "^19.2.9"
}
```

**Expected behavior**

**Actual behavior**
✘ [ERROR] Could not resolve "@vendure/admin-ui/core"

    src/app.module.ts:4:61:
      4 │ ...nt, AppComponentModule, CoreModule } from '@vendure/admin-ui/core';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./core" is not exported by package "@vendure/admin-ui":

    ../node_modules/@vendure/admin-ui/package.json:27:15:
      27 │     "exports": {
         ╵                ^

  You can mark the path "@vendure/admin-ui/core" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

### PR DESCRIPTION
**Pull request by michaelbromley**
## Summary

- Fixes the npm publish workflow to respect `publishConfig.directory` in package.json
- This restores correct publishing behavior for `@vendure/admin-ui` which needs to publish from its nested `package/` directory

Fixes #4079

## Background

When we switched from `lerna publish` to `lerna exec -- npm publish` for Trusted Publishing support, the `@vendure/admin-ui` package broke because:

- `lerna publish` respects `publishConfig.directory` 
- `npm publish` via `lerna exec` does NOT

The fix reads each package's `publishConfig.directory` and `cd`s into it before running `npm publish`.

## Test plan

- [ ] Verify the workflow syntax is correct by running a dry-run or manual dispatch
- [ ] After next publish, verify `@vendure/admin-ui` tarball contains files at root level (not under `package/` prefix)
- [ ] Verify imports like `@vendure/admin-ui/core` work correctly

### CODE REVIEW

**Comment by michaelbromley** [comment]
## Verification of fix ✅

Tested with nightly version `3.5.3-master-202601290259`:

### 1. Tarball structure
Files are at the correct level inside the package, not nested under an extra directory:
```
package/core/index.d.ts
package/fesm2022/vendure-admin-ui-core.mjs
package/catalog/...
package/login/...
etc.
```

### 2. Exports field in package.json
All subpath exports are present and correct:
```json
{
  "./core": {
    "types": "./core/index.d.ts",
    "default": "./fesm2022/vendure-admin-ui-core.mjs"
  },
  "./catalog": { ... },
  "./customer": { ... },
  "./login": { ... },
  // etc.
}
```

### 3. Import resolution
After installing in a fresh npm project, the import resolves correctly:
```
> require.resolve('@vendure/admin-ui/core')
'/node_modules/@vendure/admin-ui/fesm2022/vendure-admin-ui-core.mjs'
```

The fix is working as expected. The publish workflow now correctly respects `publishConfig.directory` for `@vendure/admin-ui`.
