### PR TITLE
fix(dashboard): Support JSON imports in the config loader

### LINKED ISSUE #4807: Dashboard dev server crashes when a custom plugin imports a JSON file
**Describe the bug**
I have a custom plugin in my Vendure project, which reads some configuration data from a local JSON file. 
Whenever I import this plugin in vendure-config.ts and try to run the dashboard in dev mode, I get a "module not found" error related to my JSON file.
After some digging, I found out that `vendureDashboardPlugin` reads `vendure-config.ts` , does a manual lookup of all relative imports (including transitive), transpiles them and then copies them to `/node_modules/@vendure/dashboard/dist/vite/.vendure-dashboard-temp`. At runtime, the transpiled `vendure-config.js` will be evaluated, but in my case it will throw an error, since the transitive import to `./google-sheet-config.json` is not found. 

This is due to the `compileTypeScript` and `collectLocalSourceFiles` functions only accounting for ts, tsx, js and jsx files, but not json. Having set `"resolveJsonModule": true` in my `tsconfig.json`, I'd expect this setting to be honoured by the dashboard compilation as well.

**To Reproduce**

1. Create a test-data.json file with any content, e.g. `{"foo":"bar"}`, next to `vendure-config.ts`.
2. Add `"resolveJsonModule": true` to tsconfig.json `compilerOptions`.
3. Add the following lines to `vendure-config.ts`:
```
import testData from './test-data.json';
console.log('TEST DATA', testData);
```
4. Start the Vendure server. You should see the test data logged to stdout.
5. Start the dashboard app in dev mode (`vite --clearScreen false`).

**Expected behavior**
Dashboard server starts in dev mode without errors.

**Actual behavior**
Dashboard server crashes with `Error: Error loading Vendure config: Error loading config: Cannot find module './test-data.json'`

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Error logs**
My original stacktrace:

```
Require stack:
- /path_to_project/vendure/node_modules/@vendure/dashboard/dist/vite/.vendure-dashboard-temp/plugins/google-sheets-integration/google-sheets-integration.plugin.js
- /path_to_project/vendure/node_modules/@vendure/dashboard/dist/vite/.vendure-dashboard-temp/vendure-config.js
Error: Cannot find module './google-sheet-config.json'
Require stack:
- /path_to_project/vendure/node_modules/@vendure/dashboard/dist/vite/.vendure-dashboard-temp/plugins/google-sheets-integration/google-sheets-integration.plugin.js
- /path_to_project/vendure/node_modules/@vendure/dashboard/dist/vite/.vendure-dashboard-temp/vendure-config.js
    at Module.<anonymous> (node:internal/modules/cjs/loader:1456:15)
    at Module._resolveFilename (/path_to_project/vendure/node_modules/tsconfig-paths/lib/register.js:103:40)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
    at Module._load (node:internal/modules/cjs/loader:1242:25)
    at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
    at Module.require (node:internal/modules/cjs/loader:1556:12)
    at require (node:internal/modules/helpers:152:16)
    at Object.<anonymous> (/path_to_project/vendure/node_modules/@vendure/dashboard/dist/vite/.vendure-dashboard-temp/plugins/google-sheets-integration/google-sheets-integration.plugin.js:21:52)
    at Module._compile (node:internal/modules/cjs/loader:1812:14)
If you are using a monorepo, you may need to provide a custom pathAdapter to resolve the paths correctly.
    at PluginContext._formatLog (file:///path_to_project/vendure/node_modules/vite/dist/node/chunks/config.js:29079:43)
    at PluginContext.error (file:///path_to_project/vendure/node_modules/vite/dist/node/chunks/config.js:29076:14)
    at PluginContext.buildStart (file:///path_to_project/vendure/node_modules/@vendure/dashboard/dist/vite/vite-plugin-config-loader.js:39:26)
    at async Promise.all (index 5)
    at async EnvironmentPluginContainer.hookParallel (file:///path_to_project/vendure/node_modules/vite/dist/node/chunks/config.js:28741:3)
    at async EnvironmentPluginContainer.buildStart (file:///path_to_project/vendure/node_modules/vite/dist/node/chunks/config.js:28751:3)
    at async file:///path_to_project/vendure/node_modules/vite/dist/node/chunks/config.js:25712:4
    at async httpServer.listen (file:///path_to_project/vendure/node_modules/vite/dist/node/chunks/config.js:25723:5)
```

**Environment (please complete the following information):**

- @vendure/core version: 3.6.4
- Nodejs version: v22.14.0
- Database (mysql/postgres etc): postgres
- Operating System (Windows/macOS/Linux): Fedora Linux
- Browser (if applicable): N/A
- Package manager (npm/yarn/pnpm): npm

**Workaround**
Extra logic in `vendure-config.ts` to not include my plugin if the process command string starts with "vite".

**Additional context**
My plugin is strictly related to the Vendure server functionality - it has nothing to do with the dashboard app. As you can see in the steps to reproduce, this error occurs also when a JSON file is imported directly in the config file, without any plugins involved.
The same error occurs when building the dashboard in production mode as well.
It's worth noting that everything was working well on version 3.5.5, but once I upgraded to 3.6.4, I started getting this error.

### PR DESCRIPTION
**Pull request by grolmus**
## Summary
The dashboard dev server (and production build) crashed with `Cannot find module './x.json'` whenever `vendure-config.ts` — or a plugin it imports — imported a local JSON file (with `resolveJsonModule`). This makes the config loader honour JSON imports.

Fixes #4807

## Root cause
`vendureDashboardPlugin` loads the Vendure config by walking its local import tree (`collectLocalSourceFiles`), transpiling each file into `.vendure-dashboard-temp`, then `import()`ing the compiled config. Since the per-file transpilation rework (#4559), `collectLocalSourceFiles` only kept files matching `/\.(ts|tsx|js|jsx)$/`, so JSON modules were silently dropped — never copied to the temp dir — and the compiled config threw `Cannot find module` at load. This worked on 3.5.5 and regressed in 3.6.x.

## Change
**`vite/utils/compiler.ts`**
- `collectLocalSourceFiles`: collect `.json` files found in the import tree (added to the visited set, no recursion — JSON has no imports to follow).
- `compileTypeScript`: copy `.json` files **verbatim** to the compiled output, preserving their relative path under the source root, instead of attempting to transpile them. Emits a warning (and skips) if a JSON asset resolves outside the config source root.

**`vite/utils/path-transformer.ts`** (ESM mode only)
- Add the `with { type: "json" }` import attribute to JSON imports (relative and path-aliased). Without it, Node throws `ERR_IMPORT_ATTRIBUTE_MISSING` when loading the compiled ESM config. Author-supplied attributes are preserved.

Copy-verbatim was chosen deliberately: it preserves the "transpile-per-file, resolve-nothing" invariant that #4559 introduced to avoid `ts.createProgram` OOMs, and is symmetric with the existing `.ts → .js` output branch.

## Test plan
Automated — `vite/tests/json-import.spec.ts` + `fixtures-json-import/` (a config that imports `./data.json` directly **and** a plugin that imports `./plugin-data.json`). Runs for both `commonjs` and `esm`:
- the config loads (`apiOptions.port === 3456`, read from the JSON);
- the transitive plugin JSON value survives (`plugins[0].pluginName === 'from-plugin-json'`);
- both JSON files are copied into the temp output;
- (esm) the emitted import carries the `with { type: 'json' }` attribute.

Verified **fails on master / passes on this branch**: cjs + esm both fail without the `compiler.ts` fix; esm fails without the `path-transformer` fix. All 63 `vite/tests` pass and the dashboard typecheck passes. Reviewed by Nigel and vendurebot (HIGH/MEDIUM applied).

No UI change, so no manual screenshots — fully covered by the config-loader unit tests.

## Scope notes / known limitations
- This fixes JSON in the **server config import tree**. JSON imported from a **dashboard extension** entry goes through Vite's own pipeline (which already handles JSON) and was never affected.
- The relative-path output assumption is shared with the existing `.ts` branch: a JSON imported from **outside** the config source root can't be placed under the temp output. The JSON branch warns and skips (actionable) rather than silently writing outside the output dir; `pathAdapter.sourceRoot` remains the supported escape hatch for monorepos.
- Static `import … from './x.json'` is covered. Dynamic `import('./x.json')` in ESM does not yet receive the attribute (possible follow-up).

---
<a href="https://app.blacksmith.sh/vendurehq/codesmith/vendure/pr/4844"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-dark-v2.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/view-with-codesmith-light-v2.svg">View with Codesmith</picture></a> <a href="https://backend.blacksmith.sh/track/enable-autofix?expires=1784371928&installation_id=128408429&pr_number=4844&repository=vendurehq%2Fvendure&return_to=https%3A%2F%2Fgithub.com%2Fvendurehq%2Fvendure%2Fpull%2F4844&signature=112c2e24a1e9b1515d26adc02363747dff557b6872e2800bf0b2490d1b5a97e3"><picture><source media="(prefers-color-scheme: dark)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://pr-comments-assets.blacksmith.sh/codesmith/autofix-with-codesmith-light.svg">Autofix with Codesmith</picture></a>
<sup>Need help on this PR? Tag <code>/codesmith</code> with what you need. Autofix is disabled.</sup>

### CODE REVIEW

**Comment by michaelbromley** [comment]
This is duplicating an existing PR:

- https://github.com/vendurehq/vendure/pull/4844

But I notice that your approach is very different. You can close this one as a duplicate but it’s also worth evaluating whether your approach has any benefits over the other PR, and if so, leave a comment there.
