### ISSUE TITLE
SMTP in Email Plugin stopped working out of the box

### ISSUE THREAD

**Issue by KSmp** [vendurehq/vendure#4920]
**Describe the bug**
SMTP in Email Plugin stopped working out of the box. After update to 3.7.0 you can't compile the app, because of type errors.

**Error logs**
If applicable, paste any relevant error messages or stack traces:

```
[server] TSError: ⨯ Unable to compile TypeScript:
[server] src/vendure-config.ts(102,17): error TS2353: Object literal may only specify known properties, and 'host' does not exist in type 'SMTPTransportOptions'.
```

**Environment:**

- @vendure/core version: 3.7.0
- Nodejs version: v24.15.0
- Operating System: macOS
- Package manager (npm/yarn/pnpm): npm

**Configuration**

```typescript
EmailPlugin.init({
    handlers: defaultEmailHandlers,
    templateLoader: new FileBasedTemplateLoader(
        path.join(__dirname, '../static/email/templates'),
    ),
    globalTemplateVars: {
        fromAddress: `${process.env.EMAIL_SENDER} ${process.env.EMAIL_ADDRESS}`,
        verifyEmailAddressUrl: `https://${siteAddress}/verify`,
        passwordResetUrl: `https://${siteAddress}/password-reset`,
        changeEmailAddressUrl: `https://${siteAddress}/verify-email-address-change`,
    },
    transport: {
        type: 'smtp',
        host: process.env.EMAIL_SMTP_HOST,
        port: Number(process.env.EMAIL_SMTP_PORT),
        secure: true,
        auth: {
            user: process.env.EMAIL_SMTP_USER,
            pass: process.env.EMAIL_SMTP_PASSWORD,
        },
    },
}),
```

**Workaround**

Add `"@types/nodemailer": "^8.0.1",` to devDependencies in package.json
